sudo: false

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc

before_script:
 - sh -e /etc/init.d/xvfb start
 
script:
 - export
 - mvn -f org.xtext.example.mydsl.parent/pom.xml clean verify