/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.TemporaryFolder
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.xbase.compiler.CompilationTestHelper
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions
import org.junit.Assert
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslCompilerTest{

	@Rule
	@Inject public TemporaryFolder temporaryFolder
	@Inject extension CompilationTestHelper
	@Inject extension ReflectExtensions

	@Test
	def void testJavaCompilation() {
		'''
		Hello World!
		'''.
		assertCompilesTo(
		'''
		package javagreetings;
		
		public class World {
			public String greeting() {
				return "Hello World!";
			}
			
			public static void main(String args[]) {
				System.out.println(new World().greeting());
			}
		}
		'''
		)
	}

	@Test
	def void testCorrectGeneratedJavaCode() {
		'''
		Hello World!
		'''.
		compile[
			compiledClass
		]
	}

	@Test
	def void testGeneratedJava() {
		'''
			Hello World!
		'''.compile [
			val obj = compiledClass.newInstance
			Assert.assertEquals("Hello World!", obj.invoke('greeting'))
		]
	}
}
